spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/velas
    username: postgres
    password: Borman15
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
  mail:
    host: smtp.gmail.com
    port: 587
    username: cjelcazador300@gmail.com
    password: zciamxtsgvjuegle


    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret_key: 6ed1eb0150e8f8fb285ec976ce500807406933985fbea5086c690eb221e53f5a
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

